name: Compile Release

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  release-linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Linux Packages
        run: |
          dnf install -y -q git cmake gcc gcc-c++ pkgconf-pkg-config \
          libstdc++.i686 libstdc++-static.i686  \
          libatomic.i686 libatomic.x86_64 \
          glibc.i686 glibc-devel.i686 \
          glfw-devel.i686 \
          libglvnd-glx.i686 \
          mesa-libGL-devel.i686 \
          protobuf-devel.i686 \
          libcurl-devel.i686 \
          zlib-ng-compat-devel.i686 \
          gtest.i686 gtest-devel.i686
          git config --global user.name github-actions
          git config --global user.email github-actions@users.noreply.github.com

      - name: Build on Linux
        run: ${GITHUB_WORKSPACE}/build-linux.sh -p ${GITHUB_WORKSPACE} -t ${{env.BUILD_TYPE}}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86
          path: |
            ${GITHUB_WORKSPACE}/build/src/game/client/client.so
            ${GITHUB_WORKSPACE}/build/src/game/server/ms.so

  release-windows:
    runs-on: $windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.28.3

      - name: Setup MSVC CLI for Windows
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build on Windows
        run: |
          cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A Win32
          msbuild ${{github.workspace}}/build/msr.sln /p:Configuration=${{env.BUILD_TYPE}} /p:Platform=win32

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: win32
          path: |
            ${{github.workspace}}/bins/release/*.dll
            ${{github.workspace}}/build/src/game/tools/scriptpack/Release/scriptpack.exe
